// Cloudflare Worker entry: serves the Next.js site (built by OpenNext into
// .open-next/) and runs the scheduled jobs that Vercel Cron used to trigger.
// @ts-ignore -- generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";

// Cron schedule (from wrangler.jsonc "triggers") → the API route it calls.
const CRON_ROUTES: Record<string, string> = {
  "5 0 1 * *": "/api/cron/ranking-snapshot",
  "30 14 * * *": "/api/cron/newsletter",
  "0 14 * * *": "/api/cron/claim-reminders",
};

export default {
  fetch: handler.fetch,

  async scheduled(event: { cron: string }, env: Record<string, string | undefined>, ctx: any) {
    const path = CRON_ROUTES[event.cron];
    if (!path) return;
    const base = env.NEXT_PUBLIC_SITE_URL || "https://soccerdadhq.com";
    const headers: Record<string, string> = {};
    if (env.CRON_SECRET) headers.authorization = `Bearer ${env.CRON_SECRET}`;
    const res = await handler.fetch(new Request(new URL(path, base), { headers }), env, ctx);
    console.log(`cron ${event.cron} → ${path}: ${res.status}`);
  },
};

// @ts-ignore -- Durable Object class used by the cache revalidation queue
export { DOQueueHandler } from "./.open-next/worker.js";
